#
# calib.tcl -- one-port Short/Open/Load (SOL) vector error correction, plus
# conversions from reflection coefficient to impedance/SWR/return loss, and
# Touchstone (.s1p) export.
#
# Depends on: complex.tcl
#
namespace eval ::aa::calib {
    namespace export sol_correct z_of_gamma swr_of_gamma rl_of_gamma \
                      new_dataset add_point write_s1p write_csv
    variable Z0 50.0
}

# ---------------------------------------------------------------- Gamma math
#
# The raw measured ratio M = V2/V1 is a *bilinear* (Mobius) function of the
# true reflection coefficient Gamma seen by the test head:
#
#     M(Gamma) = (a*Gamma + b) / (c*Gamma + d)
#
# whatever a,b,c,d happen to be for this cable/probe/channel combination at
# this frequency. Three known standards (Short: Gamma=-1, Open: Gamma=+1,
# Load: Gamma=0) give three points on that curve, which is exactly enough to
# solve the 3x4 linear system for a,b,c,d (up to one free overall scale) and
# invert the map. This is the classic 3-term (SOL) one-port error model; it
# does not require knowing a, b, c, d individually, only the three
# calibration measurements Ms, Mo, Ml and the new measurement M. Setting
# d=1, the system reduces to:
#
#     c = (Mo + Ms - 2*Ml) / (Ms - Mo)
#     Gamma(M) = (M - Ml) / [ (Mo - Ml) + c*(Mo - M) ]
#
# Unlike the more commonly quoted cross-ratio form R=(M-Ml)(Mo-Ms)/
# ((M-Ms)(Mo-Ml)), Gamma=R/(2-R), this closed form has no removable
# singularity at M==Ms, so re-measuring the short standard itself as a
# calibration sanity check (a standard QC step) works without special-casing.
#
## sol_correct M Ms Mo Ml -- return the corrected Gamma given the raw ratio M
## and the three raw calibration ratios measured with a short, an open and a
## 50 ohm load connected at the reference plane.
proc ::aa::calib::sol_correct {M Ms Mo Ml} {
    namespace import -force ::aa::complex::*
    set c   [cdiv [csub [cadd $Mo $Ms] [cmul {2 0} $Ml]] [csub $Ms $Mo]]
    set den [cadd [csub $Mo $Ml] [cmul $c [csub $Mo $M]]]
    cdiv [csub $M $Ml] $den
}

## z_of_gamma gamma ?z0? -- complex impedance for a reflection coefficient.
## An ideal open (Gamma==1) has no finite impedance; that case returns {Inf 0}
## rather than raising a division-by-zero error, so a sweep that lands exactly
## on it doesn't abort.
proc ::aa::calib::z_of_gamma {gamma {z0 {}}} {
    namespace import -force ::aa::complex::*
    if {$z0 eq ""} { set z0 $::aa::calib::Z0 }
    set denom [csub {1 0} $gamma]
    if {[cabs $denom] < 1e-9} { return {Inf 0} }
    cmul [c $z0] [cdiv [cadd {1 0} $gamma] $denom]
}

## swr_of_gamma gamma -- voltage standing wave ratio (>= 1)
proc ::aa::calib::swr_of_gamma {gamma} {
    namespace import -force ::aa::complex::*
    set m [cabs $gamma]
    if {$m > 0.9995} { set m 0.9995 }     ;# avoid a divide-by-zero at the edge
    expr {(1.0+$m)/(1.0-$m)}
}

## rl_of_gamma gamma -- return loss in dB (positive number, larger = better)
proc ::aa::calib::rl_of_gamma {gamma} {
    namespace import -force ::aa::complex::*
    set m [cabs $gamma]
    if {$m < 1e-6} { set m 1e-6 }
    expr {-20.0*log10($m)}
}

# -------------------------------------------------------------------- dataset
#
# A "dataset" is an in-memory sweep result: a dict of
#   freqs   -- list of frequencies, Hz, ascending
#   gamma   -- list of {re im}, one per frequency
# plus helpers to grow it point-by-point during a sweep and to export it.

## new_dataset -- empty dataset dict
proc ::aa::calib::new_dataset {} { dict create freqs {} gamma {} }

## add_point datasetVar f gamma -- append one swept point (call by upvar name)
proc ::aa::calib::add_point {datasetVar f gamma} {
    upvar 1 $datasetVar ds
    dict lappend ds freqs $f
    dict lappend ds gamma $gamma
}

## write_s1p path dataset ?z0? -- Touchstone version 1, single-port, RI format
#
# Format reference: freq-unit S-parameter data-format R z0, one row per
# frequency: "freq  re  im".  Any S1P-reading tool (including most antenna
# analyzer / NanoVNA-Saver-style software) can load this for cross-checking.
proc ::aa::calib::write_s1p {path dataset {z0 {}}} {
    if {$z0 eq ""} { set z0 $::aa::calib::Z0 }
    set fh [open $path w]
    puts $fh "! Touchstone S1P generated by the Tcl antenna analyzer"
    puts $fh "! freq(Hz)  Re(S11)  Im(S11)"
    puts $fh "# Hz S RI R $z0"
    foreach f [dict get $dataset freqs] g [dict get $dataset gamma] {
        lassign $g re im
        puts $fh [format "%.6f %.8f %.8f" $f $re $im]
    }
    close $fh
}

## write_csv path dataset ?z0? -- human-readable sweep table
proc ::aa::calib::write_csv {path dataset {z0 {}}} {
    namespace import -force ::aa::complex::*
    if {$z0 eq ""} { set z0 $::aa::calib::Z0 }
    set fh [open $path w]
    puts $fh "freq_Hz,R_ohm,X_ohm,|Z|_ohm,SWR,RL_dB,|Gamma|,angle_Gamma_deg"
    foreach f [dict get $dataset freqs] g [dict get $dataset gamma] {
        lassign [z_of_gamma $g $z0] R X
        set swr [swr_of_gamma $g]
        set rl  [rl_of_gamma $g]
        lassign [c2polar $g] mag rad
        puts $fh [format "%.1f,%.3f,%.3f,%.3f,%.4f,%.3f,%.5f,%.2f" \
                      $f $R $X [expr {hypot($R,$X)}] $swr $rl $mag [expr {$rad*180.0/acos(-1)}]]
    }
    close $fh
}
